# Generated by Django 5.0.7 on 2024-08-02 14:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=50)),
                ('done', models.BooleanField(default=False)),
                ('date', models.DateTimeField(default=datetime.date.today)),
            ],
        ),
    ]
